### ISSUE TITLE
Failure when finishing a download from Youtube

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.jdownloader.JDownloader#27]
Hi

When downloading a video from youtube, the failure seen in the screenshot below occurs, and I have two files in the destination folder named like this:

```
v8DhGCFtSBU_MP4_H264_1080P_30FPS_AAC_128KBIT_DASH_cc656f39610c044c36e29fb7d70b1bea.dashAudio
v8DhGCFtSBU_MP4_H264_1080P_30FPS_AAC_128KBIT_DASH_cc656f39610c044c36e29fb7d70b1bea.dashVideo
```

jdownloader installed with the installer available on jdownloader.org or from AUR downnloas videos from youtube as expected on Arch Linux.

![jd](https://github.com/flathub/org.jdownloader.JDownloader/assets/15967631/64803d16-8a23-4c9b-a0ae-0936bb7ccfbb)

**Comment by KuSh** [comment]
It's because jdownloader insist on using ffmpeg provided by the platform instead of the custom build one.
As a temporary workaround you can change jdownloader advanced settings to use /app/bin/ffmpeg and /app/bin/ffprobe in FFmpegSetup part

I've checked rapidly but didn't found something that works for every case (new install, existing install, all sorts of vids, ...)
- Using ffmpeg-full + openh264 helps but fails for some vids
- Upgrading to ffmpeg 6.0 doesn't help
- Creating configuration file before launching jdownloader does not seems to work
- I didn't found any arguments / env variable to override checked pathes

I'll try to see if I can found something that works flawlessly

**Comment by glaubersm** [comment]
Thank you very much for your interest on this issue @KuSh.
Your workaround works. :)
